#pragma once
int TestShiftOperators();
int PrintIntegerInBinary();
int ShiftOperators();
int LogicalBitwiseOperators();
int CompoundBitwiseAndAssignmentOperators();
int Masks();
int TestMasks();
int MasksExample();
int PackingColorInformation();