#pragma once
int IfStatements();
int ElseIf();
int Switch();
int ShortCircuitEvaluations();
int IntegralLogicConditions();
int TernaryOperator();
int IfConstexpr();
int IfWithInitializer();
int SwitchWithInitializer();
int VariableScopeRevisited();
int SwitchScope();